<?php

namespace backend\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "order_interval".
 *
 * @property int $id
 * @property string $date
 * @property int $interval
 * @property int $order_id
 * @property int $product_id
 * @property int $status
 * @property string $created_at
 */
class OrderInterval extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order_interval';
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                ],
                'value' => date("Y-m-d H:i:s"),
            ],


        ];
    }

    
  public function afterDelete()
    {

        Yii::warning('Удаление интервала ID ' . $this->id, 'booking_error');
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['interval','order_id','status'], 'required'],
            [['interval','order_id','product_id'], 'integer'],
            [['date','created_at'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date' => 'Дата',
            'interval' => 'Интервал',
            'product_id' => 'Товар',
            'status' => 'Статус',
            'created_at' => 'Время создания',
        ];
    }


    public static function getBusyIntervals($date,$productId){
              return self::find()->where(['date' => $date, 'product_id' => $productId,'status' => 1])->all();
    }




}
